version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: breizhsport-db
    environment:
      POSTGRES_USER: breizhsport
      POSTGRES_PASSWORD: breizhsport
      POSTGRES_DB: breizhsport
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - breizhsport-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U breizhsport"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: breizhsport-postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://breizhsport:breizhsport@postgres:5432/breizhsport?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - breizhsport-network
    depends_on:
      - postgres
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: breizhsport-backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://breizhsport:breizhsport@postgres:5432/breizhsport?schema=public
      - JWT_SECRET=votre_secret_jwt_securise
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - breizhsport-network
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  prometheus:
    image: prom/prometheus:latest
    container_name: breizhsport-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    networks:
      - breizhsport-network
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - prometheus_config:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: breizhsport-grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3005:3000"
    networks:
      - breizhsport-network
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  prometheus_config:
  grafana_data:
  grafana_config:

networks:
  breizhsport-network:
    driver: bridge
