version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: breizhsport-db
    environment:
      POSTGRES_USER: breizhsport
      POSTGRES_PASSWORD: breizhsport
      POSTGRES_DB: breizhsport
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - breizhsport-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: breizhsport-api
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=breizhsport
      - DATABASE_PASSWORD=breizhsport
      - DATABASE_NAME=breizhsport
      - JWT_SECRET=votre_secret_jwt_securise
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - breizhsport-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: breizhsport-front
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - breizhsport-network

volumes:
  postgres_data:

networks:
  breizhsport-network:
    driver: bridge
