global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    metrics_path: "/monitoring/metrics"
    static_configs:
      - targets: ["backend:3001"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
